config/routes.rb
SigepFines::Application.routes.draw do

  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout' }

  root :to => 'Fines#index'

  get '/fines/new', :to => 'Fines#new', :as => :new_fine
  post '/fines/new', :to => 'Fines#create', :as => :create_fine
  get '/fines/:id', :to => 'Fines#show', :as => :show_fine
  delete '/fines/:id', :to => 'Fines#destroy', :as => :delete_fine
  get '/fines/:id/remind', :to => 'Fines#remind', :as => :remind_fine

end

app/models/brother.rb
class Brother < ActiveRecord::Base
  attr_accessible :email, :name, :phone_number

  has_many :fines

  def create_user (password)
    @user = User.new(
      :email => self.email,
      :password => password
    )
    @user.save
  end
end

app/models/fine.rb
class Fine < ActiveRecord::Base
  attr_accessible :amount, :brother_id, :reason, :date_assigned
  belongs_to :brother
  
  validates :amount, :presence => true
  validates :amount, :numericality => { :greater_than_or_equal_to => 0.0 }

  # We use this to access number_to_currency
  # Kind of breaking MVC principles but fuck that
  include ActionView::Helpers::NumberHelper

  TWILIO_SID = CONFIG[:twilio_SID]
  TWILIO_TOKEN = CONFIG[:twilio_token]
  TWILIO_NUMBER = CONFIG[:twilio_number]

  def formatted_date
    self.date_assigned.strftime("%m/%d/%Y").to_s
  end

  def formatted_amount
    number_to_currency(self.amount)
  end

  def self.parse_date (date)
    if date.empty?
      Date.today
    else
      begin
        Date.strptime(date, '%m/%d/%Y')
      rescue ArgumentError
        Date.today
      end
    end
  end

  def self.format_date (date)
    date.strftime('%m/%d/%Y')
  end

  def phone_reminder
    @brother = self.brother

    message = "REMINDER: you have an oustanding fine of #{self.formatted_amount} for \"#{self.reason}\""

    @client = Twilio::REST::Client.new(TWILIO_SID, TWILIO_TOKEN)
    @client.account.sms.messages.create(
      :from => TWILIO_NUMBER,
      :to => @brother.phone_number,
      :body => message
    )
  end

  def email_reminder
    Notifier.reminder(self).deliver
  end

  def send_reminders
    self.phone_reminder
    self.email_reminder
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/fines_controller.rb
class FinesController < ApplicationController

  before_filter :authenticate_user!

  def index
    @fines = Fine.order("date_assigned DESC")
  end

  def show
    @fine = Fine.find(params[:id])
  end

  def new
    @fine = Fine.new
    @fine.date_assigned ||= Fine.format_date(Date.today)
  end

  def create
    @fine = Fine.new(params[:fine])

    date = params[:fine][:date_assigned]
    @fine.date_assigned = Fine.parse_date(date)

    if @fine.save
      flash[:success] = "Fine of #{@fine.formatted_amount} to #{@fine.brother.name} created"
      redirect_to root_path
    else
      @fine.date_assigned = @fine.formatted_date
      render 'new'
    end
  end

  def destroy
    @fine = Fine.find(params[:id])
    if @fine.destroy
      flash[:danger] = "Fine of #{@fine.formatted_amount} to #{@fine.brother.name} removed"
      redirect_to root_path
    end
  end

  def remind
    @fine = Fine.find(params[:id])
    @fine.send_reminders

    flash[:success] = "Phone and email reminders sent"
    redirect_to show_fine_path @fine
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fines_helper.rb
module FinesHelper
end

app/views/fines/index.html.erb
<div class="sixteen columns">
  <h2>Outstanding Fines</h2>
  <ul class="square">
    <% @fines.each do |fine| %>
      <li><a href="<%= show_fine_path(fine) %>"><%= fine.brother.name %> - <%= number_to_currency(fine.amount) %></a></li>
    <% end %>
  </ul>
  <a href="<%= create_fine_path %>">Create New Fine</a>
</div>

app/views/fines/new.html.erb
<div class="sixteen columns">
  <h2>Issue New Fine</h2>
  <%= form_for(@fine, :url => create_fine_path) do |f| %>
    <% if @fine.errors.any? %>
      <ul class="square">
        <% @fine.errors.full_messages.each do |err| %>
          <li><%= err %></li>
        <% end %>
      </ul>
    <% end %>

    <%= f.label :brother %>
    <% @options = options_from_collection_for_select(Brother.order('name ASC'), :id, :name) %>
    <%= f.select :brother_id, @options %>

    <%= f.label :amount %>
    <%= f.text_field :amount %>

    <%= f.label :reason %>
    <%= f.text_field :reason %>

    <%= f.label :date_assigned, "Date (mm/dd/yyyy)" %>
    <%= f.text_field :date_assigned %>

    <%= f.submit %>
  <% end %>
  <a href="<%= root_path %>">Back</a>
</div>

app/views/fines/show.html.erb
<div class="sixteen columns">
  <h2>Fine to <%= @fine.brother.name %></h2>
  <ul>
    <ul>Amount: <%= @fine.formatted_amount %></ul>
    <ul>Date Assigned: <%= @fine.formatted_date %></ul>
    <ul>Reason: "<%= @fine.reason %>"</ul>
  </ul>
  <%= link_to 'Send Reminder', remind_fine_path %> <br>
  <%= link_to 'Delete Fine', delete_fine_path, :method => :delete %> <br><br>

  <%= link_to 'Back', root_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SigepFines</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <div class="ten columns">
    <h1 class="header">Sigep Fines</h1>
  </div>

  <% if user_signed_in? %>
    <div class="six columns omega header user-info">
      Signed in as <%= current_user.email %> <br>
      <a href="<%= destroy_user_session_path %>">Logout</a>
    </div>
  <% end %>
  
  <hr />

  <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "alert alert-#{key}") %>
  <% end %>
    
  <%= yield %>

  <div class="sixteen columns debug">
    <%= debug(params) if Rails.env.development? %>
  </div>
</div>

</body>
</html>

app/views/notifier/reminder.text.erb
<%= @brother.name %>,

  You have a pending fine of <%= @fine.formatted_amount %> for "<%= @fine.reason %>." Please pay your fine as soon as possible.